### ISSUE TITLE
Input sanitization

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#17]
### Problem

When the template JSON is built in `Instance`, people might be able to "inject" JSON. We might want to allow to configure an input sanitization (e.g. escaping quotes or other JSON characters). However as a user might want to allow JSON inside we should make it configurable whether you want to sanitize and how (e.g. escape quotes).

### Solution

Make sanitization configurable. Should it be on a global level (all input), on a template-parameter level or both? => I think best is to actually treat text parameters as JSON text, which sanitizes it automatically. Thus when you can put `"key" : {{value}}` instead of `"key" : "{{value}}"` if `{{value}}` is a text parameter.

And then we can just add another parameter type which we call "raw" in addition to "string". This relates to #71 also.

- [ ] Introduce a new config object for templates and instances (like it is done for nomad in https://github.com/FRosner/cluster-broccoli/pull/254/files#diff-44c416010933ac7e004b47d735296d38)
- [ ] Important: If we make "string" the default parameter type then it will break all existing templates. However I think that "string" is the most reasonable default because it is safe. To avoid putting "raw" as default we can either 1) encode the Broccoli version into the template somehow and when we detect that there is no version present we choose "raw" as default, otherwise "string", or 2) add a global configuration parameter to change the default so we can allow users to have some deprecation period.
- [ ] Refactor instance parsing so I can inject the config option which parameter type to use as default.

**Comment by FRosner** [comment]
@Gerrrr this is my current status. As discussed it makes sense to factor this logic out of instance.

```
diff --git a/server/src/main/scala/de/frosner/broccoli/models/Instance.scala b/server/src/main/scala/de/frosner/broccoli/models/Instance.scala
index 47fb0b4..ff32838 100644
--- a/server/src/main/scala/de/frosner/broccoli/models/Instance.scala
+++ b/server/src/main/scala/de/frosner/broccoli/models/Instance.scala
@@ -47,16 +47,25 @@ case class Instance(id: String, template: Template, parameterValues: Map[String,
     }

   def templateJson: JsValue = {
+    val parameterInfos = template.parameterInfos
+    def sanitize(parameter: String, value: String) = {
+      val parameterType = parameterInfos.get(parameter).flatMap(_.`type`).getOrElse(ParameterType.Raw) // TODO @lunaryorn get this from config
+      val sanitized = parameterType match {
+        case ParameterType.Raw    => value
+        case ParameterType.String => JsString(value) // TODO do I need quotes here? check this in a test
+      }
+      sanitized.toString
+    }
     val templateWithValues = parameterValues.foldLeft(template.template) {
       case (intermediateTemplate, (parameter, value)) =>
-        intermediateTemplate.replaceAllLiterally(s"{{$parameter}}", value)
+        intermediateTemplate.replaceAllLiterally(s"{{$parameter}}", sanitize(parameter, value))
     }
-    val parameterDefaults = template.parameterInfos.flatMap {
+    val parameterDefaults = parameterInfos.flatMap {
       case (parameterId, parameterInfo) => parameterInfo.default.map(default => (parameterId, default))
     }
     val templateWithDefaults = parameterDefaults.foldLeft(templateWithValues) {
       case (intermediateTemplate, (parameter, value)) =>
-        intermediateTemplate.replaceAllLiterally(s"{{$parameter}}", value)
+        intermediateTemplate.replaceAllLiterally(s"{{$parameter}}", sanitize(parameter, value))
     }
     Json.parse(templateWithDefaults)
   }
diff --git a/server/src/main/scala/de/frosner/broccoli/models/ParameterInfo.scala b/server/src/main/scala/de/frosner/broccoli/models/ParameterInfo.scala
index 8e91262..6496d7a 100644
--- a/server/src/main/scala/de/frosner/broccoli/models/ParameterInfo.scala
+++ b/server/src/main/scala/de/frosner/broccoli/models/ParameterInfo.scala
@@ -3,7 +3,11 @@ package de.frosner.broccoli.models
 import play.api.libs.json.Json

 // TODO add display name and description also
-case class ParameterInfo(id: String, name: Option[String], default: Option[String], secret: Option[Boolean])
+case class ParameterInfo(id: String,
+                         name: Option[String],
+                         default: Option[String],
+                         secret: Option[Boolean],
+                         `type`: Option[ParameterType])

 object ParameterInfo {
```

**Comment by Gerrrr** [comment]
After discussing with @FRosner we decided to change the implementation of the `string` type. `TemplateRenderer.sanitize` should escape the string instead of converting the parameter value to a valid JSON string with an additional pair of quotes.

**Comment by FRosner** [comment]
What's the status here, @Gerrrr? Is it done? I think we included it, no?

**Comment by Gerrrr** [comment]
It is done. BTW we also have notes on backward incompatibilities in the wiki.
