### ISSUE TITLE
Make templates parsed as JSON

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#2]
### Problem

Right now, templates are parsed off of a JSON template for the nomad job + a description text file + an image. In order to make this more structured and be prepared for also a create / update REST endpoint for templates later on, we might want to standardise it.
### Solution
- [ ] Instead of a `description.txt`, have another JSON document with meta information (like template name, description, etc.).
- [ ] Update https://github.com/FRosner/cluster-broccoli/wiki/Template-Definition

**Comment by rolandjohann** [comment]
The current templating process is that the templates and descriptions (and maybe meta of a template) will be stored as plain files at disk. I'll suggest introducing a DBMS like postgres that will handle that. The REST API could handle uploading of nomad hcl job specs. Maybe at the job hcl the templatable members can contain some specific value so the parsing service is able to automatically generate the proper meta for which members are templatable, etc. With that there also can be a frontend GUI implemented to provide the generation of templates

**Comment by FRosner** [comment]
Agreed @rmmjohann. Long term I want templates also to be mutable and persisted in some DB. Also your suggestions regarding the templating engine + GUI make a lot of sense. However, from my point of view there is not a hurry to implement it, because in my current use cases, templates are rather static and other features like a form based login + REST endpoint security are more important. But I will consider it as soon as I have the time 👍

**Comment by FRosner** [comment]
Done already.
