### ISSUE TITLE
Logged in but I see the login form

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#219]
![grafik](https://user-images.githubusercontent.com/3427394/26926499-406e443e-4c4e-11e7-8ce5-bd9dc6da363e.png)

**Comment by FRosner** [comment]
@stolho were you able to reproduce?

**Comment by stolho** [comment]
@FRosner no, after that tried the same steps - enter incorrect password 2 times, get error message and then enter correct one, but can't reproduce.

**Comment by FRosner** [comment]
No worries I will take a look and see what I can find.

**Comment by stolho** [comment]
One thing just remembered - can be that I have expired session when the issue happened.

**Comment by FRosner** [comment]
Were you able to still use the UI in that state (create, modify, start instances), @stolho?

**Comment by FRosner** [comment]
Were you accessing the UI through a reverse proxy when it happened, @stolho?

**Comment by FRosner** [comment]
I see from the screenshot that the websocket got terminated by a `ConnectError`

```
WsConnectError ( url, error ) ->
            let
                l =
                    Debug.log "ConnectError" ( url, error )
            in
                ( { model | wsConnected = False }
                , CmdUtils.delayMsg (5 * Time.second) AttemptReconnect
                )
```

The UI only gets reset if there is a connection lost.

```
WsConnectionLost url ->
            let
                l =
                    Debug.log "ConnectionLost" url
            in
                ( { model
                    | wsConnected = False
                    , aboutInfo = Nothing
                    , templates = Dict.empty
                    , instances = Dict.empty
                  }
                , Ws.connect model.location
                )
```

Maybe what happened is that `WsConnectionLost` was not triggered when the WS died. Then it tried to reconnect, failed, but the model was not reset.

**Comment by FRosner** [comment]
I found one way to reproduce a similar behaviour. I am not sure if it is the same cause but it has the same symptom. When the session timeout is 1 second, the session becomes invalid before the next scheduled verify check gets sent. The check fails but the websocket is still connected.

Actually in the screen shot you can see that although the session is not valid anymore the websocket gets still reconnected.

I propose we either

- disconnect the websocket gracefully on the UI side if verification fails, or
- ignore the verification error if the websocket is still connected

**Comment by FRosner** [comment]
I decided to ignore verification errors if the websocket is still connected. This way makes most sense for the user as with a websocket connection running everything is fine for him. He doesn't have to worry about not being able to login after refreshing the page until he refreshes it.

Let's deploy this and see if the error still happens.
