### ISSUE TITLE
More powerful template engine

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#224]
### Problem

Right now we can only have simple string replacement. It would be cool to have a more powerful template engine allowing control structures likes conditions, loops, etc.

We only need to take care that there is a way to identify the variables required so we can still ask the user for the input accordingly.

### Solutions

Use [https://github.com/HubSpot/jinjava](Jinjava). The process would be the following:

- When creating a template, you can use Jinja2 syntax.
- When the templates are loaded, we cannot really render or check anything as Jinjava needs parameter values in order to render.
- As soon as the template is rendered (which is before submitting the instance job to Nomad), we take the parameter values specified by the user and feeding them to Jinjava for rendering.

Because Jinja allows for locally bound variables (e.g. in loops), we can no longer extract all possible variables from the template. So the UI does not know which parameters to display. Instead, when rendering the UI we have to rely on the `template.conf` information.

### VIAC (Very Important Acceptance Criterion)

- It is not possible to have an unbound variable in the Jinja template to which there is no information in the `template.conf` and then still bind it by submitting the parameter values including this variable. Instead, Broccoli should fail.

### ToDo

- [x] The Jinja template characters (`{{`, and `}}`) will conflict with the template stanza from Nomad 0.5.0. However the template characters from Nomad are [configurable](https://www.nomadproject.io/docs/job-specification/template.html#left_delimiter) so that should be fine. Can Jinjava also have configurable template characters?
- [x] The user specifies all possible parameters in the parameter info section of the `template.conf`. If those parameters are not enough to completely render the template, Jinjava should fail. It knows this because there are unbound variables. Can we fail on unbound variables?

---

# Documentation changes

## https://github.com/FRosner/cluster-broccoli/wiki/Upgrading-to-0.8.0

**Templates**

Templates are now rendered with [Jinjava template engine](https://github.com/HubSpot/jinjava). Because of this, there are several changes breaking backwards compatibility:
* Variables can no longer contain dashes. In order to automatically convert dashes in the variable names in instances and templates, you can set `broccoli.templates.convert-dashes-to-underscores` to `true`.
* Broccoli no longer automatically discovers template variables. You have to explicitly specify all variables in `template.conf`. To fix existing instances, please run the upgrade script:
    - `nomad stop cluster-broccoli`
    - backup instances directory
    - `python script/instances-0.7.0-to-0.8.0.py /path/to/broccoli/instances`
    - `nomad start cluster-broccoli`

**Configuration Changes**

It is possible to set [Jinjava config settings](https://static.javadoc.io/com.hubspot.jinjava/jinjava/2.4.0/index.html?com/hubspot/jinjava/JinjavaConfig.html) through Broccoli. The default values are kept the same as in Jinjava, unless stated otherwise. For documentation on those parameters please refer to the original project https://github.com/HubSpot/jinjava.

Here is the list of Jinjava settings configurable through Broccoli:

* `broccoli.templates.jinjava.trim-blocks` (defaults to `false`)
* `broccoli.templates.jinjava.lstrip-blocks` (defaults to `false`)
* `broccoli.templates.jinjava.max-render-depth` (defaults to `10`)
* `broccoli.templates.jinjava.read-only-resolver` (defaults to `true`)
* `broccoli.templates.jinjava.enable-recursive-macro-calls` (defaults to `false`)
* `broccoli.templates.jinjava.fail-on-unknown-tokens` (defaults to `true`)
* `broccoli.templates.jinjava.max-output-size` (defaults to `0`)
* `broccoli.templates.jinjava.nested-interpretation-enabled` (defaults to `true`)

---

### Nomad JSON Template File

The template file is a Jinja2 template of a [Nomad job file in JSON format](https://www.nomadproject.io/docs/jobspec/json.html). In order to allow for customization (e.g. launching multiple instances of the same job with different names or settings), you can add parameters. A parameter is enclosed in two curly brackets (`{{...}}`). For more details about the template syntax please refer to the [Jinja2](http://jinja.pocoo.org/) and [Jinjava](https://github.com/HubSpot/jinjava/) documentation.

**Note:** Nomad jobs have a [template stanza](https://www.nomadproject.io/docs/job-specification/template.html) that uses Consul Template. Both Jinja2 and Consul Template use curly brackets for variables by default. To resolve the conflict between template engines, one can use Nomad's [LeftDelim](https://www.nomadproject.io/api/json-jobs.html#leftdelim) and [RightDelim](https://www.nomadproject.io/api/json-jobs.html#rightdelim) parameters to change Consul Template's syntax (requires Nomad >= 0.5.5).

#### Parameter Information

The template file usually contains different parameters. These parameters must be declared in the meta information file. They can also have additional properties.

---

**UPD 1**

Document only configurable jinjava options.

**UPD 2**

Add a note about a Nomad template stanza.

**Comment by FRosner** [comment]
Hi @Gerrrr 

I guess we should document this change in the Wiki, right? Would you mind adding some documentation to the description of the ticket that I can then include into the Wiki on release? We probably don't have to explain how Jinja works but maybe we give an example of a simple parameter and then also an {{if}} or loop to show the difference between local variables and global template variables.

**Comment by FRosner** [comment]
@Gerrrr, do you think we should rename the `template.json`, as it is not really a JSON? `template.j2` or `template.json.j2`?

**Comment by Gerrrr** [comment]
I think that renaming `template.json` to `template.json.j2` is a good idea! Thanks!

**Comment by FRosner** [comment]
Is it really? I'm asking. It will mean another breaking change. But on the other hand it will make it more obvious that it doesn't have to be a JSON. Any other name that makes more sense? What if we support a different template engine later?

According to Jinja2 there is no extension. Ansible uses .j2 but that's not the standard.

Will it add any value if we call it .j2?

**Comment by Gerrrr** [comment]
I think that it makes sense for the reason you mentioned - to show that it is not a JSON, but a Jinja2 template of a JSON file. Though .j2 is not a standard extension, it is ± commonly used to "symbolize" that the file is a jinja2 template. Moreover, If we support another template engine later, we would be able to differentiate the template to use by picking the one with the right extension.

Of course it is a breaking change, but we also changed `meta.json` to `template.conf` in the same release. IMO it would not create a lot of additional effort, but will make the template structure cleaner.
