### ISSUE TITLE
Docker push happens even if tests fail

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#236]
### Problem

e.g. https://travis-ci.org/FRosner/cluster-broccoli/builds/250439425

### Possible Solutions

- tell Travis to abort when one line fails
- move docker commands to after_success (ugly because if the push fails the build still succeeds)
- see if Travis supports dependent build stages and make the docker stage depend on the test stage

**Comment by swsnr** [comment]
Just for the record, stages introduces in #235 should also fix this.

**Comment by FRosner** [comment]
Thx @lunaryorn!
