### ISSUE TITLE
Instance does not show all services

### ISSUE THREAD

**Issue by oribaldi** [FRosner/cluster-broccoli#241]
Seems that a job does not show services for some reason. After looking into it we discovered that this job was having multiple task groups. Could it be that your JSON parsing code does not work properly with multiple task groups?

https://github.com/FRosner/cluster-broccoli/blob/74e56050add6ceb760c9937145433c173a6cec1a/app/de/frosner/broccoli/services/NomadService.scala#L137

```
[ERROR] NomadService - Requesting services for service-name failed: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List(error.expected.jsarray),WrappedArray())))))
```

**Comment by FRosner** [comment]
The problem seems to be that your job returns `null` and not an empty array when asking for the services:

```
"Services": null,
```

When I tried to reproduce it, my Nomad was giving me an empty array. Not sure why. I'm gonna have to deal with nulls then.

**Comment by oribaldi** [comment]
Ok, I think that's my fault. I will change the job specification to:
```
"Services": []
```
Because it should be a list according to the documentation.

I will try again with the new specification and let you know.

---- EDIT -----

It should be:
```
"Services": null
```
and not an empty array.

The problem might also be that you are not considering the services of all the task groups?

**Comment by FRosner** [comment]
The thing is that I also used `null` in order to reproduce it but when I submit the job and then query it through `/v1/job/<id>` it gives me an empty array. But your job gives me `null`. Anyway my code should not behave in a weird way when there is a `null` value so I gotta validate that :)

Thanks for reporting.
