### ISSUE TITLE
Resource Allocation Information

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#287]
### Problem

When configuring the CPU, disk and memory of your instances it is often a bit of a guesstimate.

### Solution

For each task, show the resource information, like it is done through `nomad alloc-status`. We should start with visualizing CPU and memory for now.

```
Task "broccoli" is "running"
Task Resources
CPU          Memory           Disk  IOPS
826/500 MHz  595 MiB/2.0 GiB  0 B   0
```

#### Branch

https://github.com/FRosner/cluster-broccoli/tree/frosner/issue-287-resource-allocation-information-ui-draft

#### Overview

![image](https://user-images.githubusercontent.com/3427394/29625550-5143704e-882c-11e7-900f-5400c3d97576.png)

#### Hover Title

![untitled 2](https://user-images.githubusercontent.com/3427394/29625887-56b0f35c-882d-11e7-89ca-3140df91ee4a.png)

#### Showing the Percentage

![image](https://user-images.githubusercontent.com/3427394/29626062-dcca3f02-882d-11e7-95e5-258983a5f5dd.png)

#### Color Coding (Green, Yellow, Red, Red Striped)

![image](https://user-images.githubusercontent.com/3427394/29626228-5a5aa114-882e-11e7-8107-2f1375257f42.png)

### Open Points

- As we need to request this information from each individual nomad client we probably don't want to do this very often. Actually it would be optimal to do it lazily (so only when someone expands an instance) and maybe refresh it every 5 seconds or something. It doesn't have to be too interactive as we can use a more sophisticated infrastructure involving a metrics DB etc. for that. So it should be an indication whether your planned resources are planned well.
- It would be great to have an intuitive visualization and then show the actual numbers only when hovering. We could use a horizontal bar (like in a progress bar). We only need to have a special encoding for values that exceed the visual maximum (like 800 / 500 MHz CPU).

**Comment by swsnr** [comment]
I'll take a look next week to figure out how to get the resources from the Nomad API.

**Comment by swsnr** [comment]
@FRosner Which resources are we interested in?

I presume CPU and memory, but what about disk?  And network speed?  I can't find the latter two in the corresponding Nomad API…

**Comment by FRosner** [comment]
Let's start with CPU and memory. AFAIK Nomad does not really limit disk, @Gerrrr? Also we don't have any use case where disk plays a role at the moment. Network is not configurable right now.

It is certainly possible that we add it later but right now we don't need it.

**Comment by swsnr** [comment]
:blush:
