### ISSUE TITLE
UI not usable after Nomad restart

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#291]
## Problem

When Nomad is not reachable while the UI is initialized and an instance is expanded, the allocated tasks cannot be loaded. When Nomad becomes reachable again, the page needs to be refreshed for the allocated tasks to show up because the UI keeps showing the spinner otherwise.

Also the instance control buttons don't work. You cannot start or stop a job until refreshing the page.

## How To Reproduce

- Start Cluster Broccoli (don't start Nomad, yet)
- Create a new HTTP Server instance
- Expand this instance and observe allocated tasks not being fetched

![image](https://user-images.githubusercontent.com/3427394/29771968-a7b00cb2-8bf6-11e7-8551-83c7b1a0f17f.png)

- Start Nomad and observe that allocated tasks are still not being fetched although Nomad is reachable

![image](https://user-images.githubusercontent.com/3427394/29771985-c2c60dc6-8bf6-11e7-852a-842237b0d08e.png)

- Refresh web page and see the correct message "No tasks have been allocated, yet."

![image](https://user-images.githubusercontent.com/3427394/29771999-dae6e6be-8bf6-11e7-9ddc-e1cc0bb40b09.png)

## Expected Behaviour

- UI stops working when Nomad is not reachable
- UI starts working again when Nomad is reachable again without having to refresh

**Comment by swsnr** [comment]
@FRosner Did you look at the websocket messages exchanged?  Did any errors appear in the console?

**Comment by FRosner** [comment]
No error message. The run request is submitted but nothing happens:

![image](https://user-images.githubusercontent.com/3427394/29772521-742c8cbe-8bf9-11e7-8141-c52c45e4c25e.png)
