### ISSUE TITLE
No docker image with v 0.70

### ISSUE THREAD

**Issue by mastaofdisasta** [FRosner/cluster-broccoli#318]
Docker image contains version 0.8.0-SNAPSHOT. No image with 0.7.0 available

**Comment by FRosner** [comment]
Looks like the docker stage of the build did not run: https://travis-ci.org/FRosner/cluster-broccoli/jobs/288595711.

I restarted it.

**Comment by FRosner** [comment]
Looks like when migrating to this sbt docker plugin the tagging by git tag functionality went away :O

**Comment by FRosner** [comment]
If you want you can use `4382ced7` for now (that's the tag) until I fixed the tags being pushed again.

**Comment by FRosner** [comment]
@lunaryorn do you know how to add back the functionality that the image gets also tagged with the git tag? I guess it's somewhere around this line https://github.com/FRosner/cluster-broccoli/blob/master/build.sbt#L50

**Comment by swsnr** [comment]
@FRosner No, I do not, and I can't help you here.

**Comment by FRosner** [comment]
Looks like we gotta use [`dockerBuildOptions`](http://sbt-native-packager.readthedocs.io/en/latest/formats/docker.html#publishing-settings) and specifying multiple `-t`s. I can type `show dockerBuildOptions` in the sbt shell to see the current value.

**Comment by FRosner** [comment]
0.7.0 should now be available. Thanks and sorry for the inconvenience.
