### ISSUE TITLE
Use atomic move operation in file system instance storage

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#337]
### Problem

Right now, if Broccoli crashes during a [write operation](https://github.com/FRosner/cluster-broccoli/blob/1165d42c61c9bb47c52a2ee19c21a2e8ae09c4ed/server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala#L80) using the file system instance storage, this might lead to corrupted data.

### Solution

- Create `<instance-id>.json_tmp` inside the instance dir and write the content there.
- Use [`Files.move`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...)) with [`StandardCopyOption.ATOMIC_MOVE`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardCopyOption.html#ATOMIC_MOVE) to overwrite `<instance-id>.json` afterwards.

**Comment by IshmeetKaur** [comment]
Please review @FRosner 
https://github.com/FRosner/cluster-broccoli/pull/339
