### ISSUE TITLE
how to start with couchdb?

### ISSUE THREAD

**Issue by lgfausak** [FRosner/cluster-broccoli#359]
I have been using the broccoli for a while, really like it!  I run it from docker. I would like to try using the couchdb interface. It is not clear to me how to configure this. I see that a .conf file can add and delete configuration, because you can't select couchdb with a -D in the docker args. There is documentation stating that I have to select the model, which I have tried by creating a /couchdb.conf file in the docker executable before I start bin/cluster-broccoli. However, my messages on stdout still indicate that the file storage module is being used.  My couchdb.conf file looks like this: 
```
play.modules.disabled += "de.frosner.broccoli.instances.storage.filesystem.FileSystemStorageModule"
play.modules.enabled += "de.frosner.broccoli.instances.storage.couchdb.CouchDBStorageModule"
```

but that doesn't seem to work.  I don't know scala, maybe this is obvious, but I can't figure out how to configure it!

**Comment by FRosner** [comment]
Hi! Do you mind moving the discussion to the [gitter channel](https://gitter.im/FRosner/cluster-broccoli)?
