### ISSUE TITLE
Error -- Failed to update instance

### ISSUE THREAD

**Issue by pravicloud** [FRosner/cluster-broccoli#372]
Could you pleaes check this isssue. I am note able to run the jobs on broccoli..

Please help me to resolve the issue.

Failed to update instance: "java.net.URISyntaxException: Illegal character in scheme name at index 0: 172.31.37.5:4646/v1/jobs" -- broccoli browser 

[ERROR] [application-akka.actor.default-dispatcher-3] [d.f.b.c.WebSocketController] - Message handler threw exception for message GetInstanceTasks(test): scheme
java.lang.NullPointerException: scheme -- terminal

**Comment by sohaibiftikhar** [comment]
The URL format is `<scheme>://<ip>:<port>`. Try using `http://172.31.37.5:4646` as your nomad URL in your conf.

**Comment by pravicloud** [comment]
Thasnks for the quick responce. 
I have used  th below docker command only 
docker run -p 9000:9000 frosner/cluster-broccoli \
  -Dbroccoli.nomad.url=172.31.37.5:4646 \
  -Dbroccoli.consul.url=172.31.37.5:8500

Please help me.

**Comment by pravicloud** [comment]
Now i got new error:

Failed to update instance: "de.frosner.broccoli.services.NomadRequestFailed: Nomad request http://172.31.37.5:4646/v1/jobs failed. Status code 500"

could you please check it

**Comment by pravicloud** [comment]
09:26:54.777 [INFO] [application-akka.actor.default-dispatcher-5] [d.f.broccoli.services.NomadService] - Sending job definition to http://172.31.45.252:4646/v1/jobs
09:26:54.798 [ERROR] [application-akka.actor.default-dispatcher-5] [d.f.b.services.InstanceService] - Error updating instance: de.frosner.broccoli.services.NomadRequestFailed: Nomad request http://172.31.45.252:4646/v1/jobs failed. Status code 500

**Comment by sohaibiftikhar** [comment]
I am sorry but this seems unrelated. You need to check your nomad logs for this.
