### ISSUE TITLE
Start/Stop buttons in Green/Red are misleading

### ISSUE THREAD

**Issue by pliguori** [FRosner/cluster-broccoli#38]
Currently, a line with a "running" service is looking red because the "Stop" button is red, and a line with a "stopped" service looks green because the "Start" button is green. This is misleading.

I would propose to have a green "running" and a red "stopped" status labels.
For action buttons, something like glyphicon-play and glyphicon-stop could be used.

**Comment by FRosner** [comment]
Thank you for your contribution @pliguori. Would you like to submit a pull request or shall I pick it up when I have some free time?

Do you enjoy using Cluster Broccoli? Why don't you leave a star :)

**Comment by pliguori** [comment]
done!
PS. ignore the first 2 commits here, the valid one is the one in the PR. I was trying to play with your commit message style :)

**Comment by pliguori** [comment]
<img width="1020" alt="schermata 2016-08-22 alle 22 42 49" src="https://cloud.githubusercontent.com/assets/1300589/17871013/0e82290e-68ba-11e6-947e-e412e21af625.png">

Here is how it should look like

**Comment by FRosner** [comment]
![image](https://cloud.githubusercontent.com/assets/3427394/18149373/0b70cc98-6fe0-11e6-9bab-229b5d2d354d.png)
