### ISSUE TITLE
Show logs of nomad job

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#44]
Progress on https://github.com/FRosner/cluster-broccoli/projects/2

### Problem

When a nomad job is started through the UI, it would be nice to be able to get logs about this job. A Broccoli instance can create one (one-time batch or system jobs) or multiple (periodic jobs) Nomad jobs. A Nomad job has one or multiple allocations which can be pending, running, failing or finishing. The UI should reflect this in a consistent but understandable way.

### Solution

The Broccoli HTTP API should have a possibility to query for out and err logs of an instance and the UI should show it somewhere.
### References
- https://www.nomadproject.io/docs/http/client-fs.html

**Comment by swsnr** [comment]
# TODO:

- [x] Find out how to get access to the client that holds an allocation, as `client/fs` requests must be made to the client that runs an allocation, see <https://www.nomadproject.io/docs/http/client-fs.html>. Looks as if we can just get the HTTP address of the corresponding node.

# How to get hold of logs

```console
# Get tasks of a job
$ http get localhost:4646/v1/job/test | jq '.TaskGroups | map(.Tasks) | flatten | map(.Name)'
[
  "http-task"
]
# Get allocations of a job
http get localhost:4646/v1/job/test/allocations | jq 'map({ID: .ID, NodeID: .NodeID})'
[
  {
    "ID": "699a84f9-1829-e6cd-d677-1ed10d8c9253",
    "NodeID": "fb2170a8-257d-3c64-b14d-bc06cc94e34c"
  }
]
# Get HTTP address of a node of an allocation
$ http get localhost:4646/v1/node/fb2170a8-257d-3c64-b14d-bc06cc94e34c | jq '.HTTPAddr'
"127.0.0.1:4646"
# Get logs for a task in an allocation (from the node HTTP address as received above)
$ http get "localhost:4646/v1/client/fs/logs/699a84f9-1829-e6cd-d677-1ed10d8c9253?follow=0&task=http-task&type=stderr" | jq -r .Data | base64 -D
```

We probably need to show all tasks & their allocations in the UI, and then provide an option to get logs per each combination of task & allocation.

**Comment by swsnr** [comment]
@FRosner Should be fixed, shouldn't it?  If not, can you please un-assign me?
