### ISSUE TITLE
Put JS libraries in assets?

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#5]
### Problem

Right now, all JS libraries are loaded from the internet. This has two problems. First, it doesn't work if there is no internet. Second, it is annoying if the internet connection is slow.
### Solution

Is there any problem in just putting all JS files in assets?

**Comment by rolandjohann** [comment]
There has to be some build process like grunt/gulp/webpack for managing and building the frontend files/libs. That can also be used to run the angular tests (unit/e2e) at development time

**Comment by FRosner** [comment]
Agreed @rmmjohann. Would you like to support me on that topic as I have not a lot of experience with JS?
