### ISSUE TITLE
Websocket / SSE

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#85]
Instead of polling every 1 second it would be a nice option to have a websocket connection / SSE between the Broccoli UI and the back-end.

- [ ] We still need the normal HTTP API for non-UI usage so there should be a web socket API in addition.
- [ ] we should know how to support switching on wss (TLS)

### Authentication

```
 Controller with AsyncAuth {

  def socket: WebSocket = WebSocket.acceptOrResult[String, String] { implicit request =>
    authorized(isLoggedIn).map {
      case Left(_) => Left(Forbidden)
      case Right((user, _)) =>
        Right {
          ActorFlow.actorRef(out => {
            actorManager.agentWebsocketServer ! (out, user.id.get)
            AgentClientActor.props(out, actorManager, user)
          })
        }
    }
  }
   }
```

### References

- http://runkalrun.blogspot.de/2016/01/server-sent-events-sse-using-scala-akka.html
- https://www.playframework.com/documentation/2.5.x/ScalaWebSockets#Handling-WebSockets-with-iteratees
- http://package.elm-lang.org/packages/elm-lang/websocket/1.0.2/ + https://guide.elm-lang.org/architecture/effects/web_sockets.html

**Comment by FRosner** [comment]
@IshmeetKaur what do you think about SSE? Would it be difficult to integrate with restangular?

**Comment by IshmeetKaur** [comment]
I have not worked on it but probably I can look into it and implement some examples if you want.

**Comment by FRosner** [comment]
No examples just an opinion whether it would be possible :)
