### ISSUE TITLE
Creating CRUD Services for Instances

### ISSUE THREAD

**Issue by IshmeetKaur** [FRosner/cluster-broccoli#92]
- [ ] The current functionalities of creating ,retrieving ,updating and deleting the instance under the templates should be available as a service.
- [ ] There should be automated tests for this service

**Comment by IshmeetKaur** [comment]
The services should be defined explicitly for all the end points.So, there should be separate services for
Templates,Instances and About endpoints talking to the main controller.
Also, the unit test for each services and the main controller should be defined separately.

**Comment by FRosner** [comment]
@IshmeetKaur it seems that the function for changing the template is missing:

![image](https://cloud.githubusercontent.com/assets/3427394/20094511/d3bac87e-a5a1-11e6-9077-628509449659.png)

**Comment by FRosner** [comment]
It is probably because of `instCtrl.dropdown.templates` being empty. Because the code in `newInstanceModal.html` is still there.

```
<div class="input-group" ng-if="instCtrl.dropdown.templates != null">
```
